### PR TITLE
Line wrap the option descriptions

### LINKED ISSUE #36: Reflow long option descriptions
Long option descriptions are not reflowed and automatically wrap, leading to ugly results.

### PR DESCRIPTION
**Pull request by bmesuere**
This enables wrapping the option description and fixes #36.
I'm not quite sure if this is the right approach to fixing this, so I'm waiting on approval to add tests.

### CODE REVIEW

**Comment by ddfreyne** [comment]
Looks good, although I’d like to have tests for this. Where does the `length + 10` come from?

**Comment by bmesuere** [comment]
The `+10` comes from the extra whitespace added in https://github.com/ddfreyne/cri/blob/master/lib/cri/help_renderer.rb#L207 on top of the given length. There are 4 spaces in the beginning of the line and the `+6` adds an extra 6.

I'll add some tests to `test_string_formatter.rb`.

**Comment by ddfreyne** [comment]
Sounds good. Could you create constants `OPT_DESC_SPACING = 4` and `OPT_DESC_INDENT = 6` for clarity?

**Comment by bmesuere** [comment]
I added the constants you suggested and a test. While I was at it, I also made a constant for the line width (78).

**Comment by ddfreyne** [comment]
Could you create a `def test_help_with_wrapped_options` (or somesuch) in _test/test_command.rb_ that provides a high-level test for this feature?

After that, I’ll merge!

**Comment by bmesuere** [comment]
If I add the test to test_command.rb, Rubocop complains over the length of the class definition:
```
Running RuboCop...
Inspecting 30 files
.........................C....

Offenses:

test/test_command.rb:4:3: C: Class definition is too long. [448/436]
  class CommandTestCase < Cri::TestCase
  ^^^^^

30 files inspected, 1 offense detected
RuboCop failed!
```

```ruby
    def test_help_with_wrapped_options
      def $stdout.tty?
        true
      end

      cmd = Cri::Command.define do
        name 'build'
        flag     nil, :longflag,     'This is an option with a very long description that should be wrapped'
      end
      help = cmd.help

      assert_match(/^       \e\[33m--longflag\e\[0m      This is an option with a very long description that$/, help)
      assert_match(/^                       should be wrapped$/, help)
    end
```

**Comment by ddfreyne** [comment]
Oh, meh. I’m inclined to disable that RuboCop for now. There’s some refactoring that could be done (such as splitting out the help generation tests) but for the time being, I am OK with disabling the cop:

```yaml
Metrics/ClassLength:
  Enabled: false
```

**Comment by bmesuere** [comment]
All done!

**Comment by ddfreyne** [comment]
Thanks!

**Pull request merged**
