### PR TITLE
Add support for Ruby 3.0

### PR DESCRIPTION
**Pull request by joshRpowell**
with Ruby 3.0.0 I see the following error: 

```
cri-2.15.10 requires ruby version ~> 2.3, which is incompatible with the current version, ruby 3.0.0p0
```

https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/

### CODE REVIEW

**Comment by joshRpowell** [comment]
requires some more work with Rubocop:

```
.rubocop.yml: Metrics/LineLength has the wrong namespace - should be Layout
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file.
Please also note that can also opt-in to new cops by default by adding this to your config:
  AllCops:
    NewCops: enable
Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: true
Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: true
Lint/DuplicateBranch: # (new in 1.3)
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true
Lint/EmptyBlock: # (new in 1.1)
  Enabled: true
Lint/EmptyClass: # (new in 1.3)
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: true
Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true
Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: true
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true
Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true
Style/CollectionCompact: # (new in 1.2)
  Enabled: true
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true
Style/HashExcept: # (new in 1.7)
  Enabled: true
Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true
Style/NilLambda: # (new in 1.3)
  Enabled: true
Style/RedundantArgument: # (new in 1.4)
  Enabled: true
Style/SwapValues: # (new in 1.1)
  Enabled: true
For more information: https://docs.rubocop.org/rubocop/versioning.html
Inspecting 34 files
....WWW...CCCW.C.CCCCCC...........
```

**Comment by ddfreyne** [comment]
Hi Josh! First of all, thanks for taking the time to whip up this PR.

Ruby 2.3 support unfortunately can’t be dropped due to the [compatibility policy](https://github.com/ddfreyne/cri#compatibility-policy) that is in place.

I’ve created a PR of my own, with some of your changes pulled in: #111.

**Comment by ddfreyne** [comment]
Correction about the compatibility policy: The last two Ubuntu LTS and the last two macOS releases have at least Ruby 2.5, and so Ruby 2.3 and Ruby 2.4 can both be dropped. I’ll take care of that in a separate PR.

**Comment by joshRpowell** [comment]
thanks @ddfreyne any plans on tagging a new release with your changes in #111 ?

**Comment by ddfreyne** [comment]
@joshRpowell 2.15.11 is released: https://github.com/ddfreyne/cri/releases/tag/2.15.11

**Pull request closed without merging**
